[project]
name = "test-technique-chemosens"
version = "0.1.0"
description = "technical test of a job position"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.30.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
]
